### ISSUE TITLE
Pinned Python version?

### ISSUE THREAD

**Issue by jGaboardi** [martinfleis/sdss22-workshop#10]
https://github.com/martinfleis/sdss22-workshop/blob/7d36efe5cce43bb94abf6ad475576720ca3598e9/environment.yml#L4

In the environment we are specifying a Python version. I am playing the binder now and seeing that it is Python 3.7 environment being created... no good. I propose we pin Python 3.10 here.

**Comment by martinfleis** [comment]
You can try pinning. We'll see. I'm going to bed so feel free to merge changes to debug that.
