### ISSUE TITLE
Final stuff?

### ISSUE THREAD

**Issue by jGaboardi** [martinfleis/sdss22-workshop#23]
@martinfleis Any last stuff you can think of for tomorrow?

**Comment by martinfleis** [comment]
I'll need a lot of sugar. The PhD reviews I'll be at since 8am (the talk is at 14:45 Prague time, right?) are exhausting :D. 

We just try to open binder now and then to ensure the container is built and ready but that should be it.

**Comment by jGaboardi** [comment]
Yep! 8:45 EDT // 2:45 CEST.

**Comment by jGaboardi** [comment]
I'd like to make a Zenodo DOI for this presentation/workshop to properly curate. Would you be against that?

**Comment by martinfleis** [comment]
Nope, but I'll need to do that I guess and won't be able to before the actual workshop.

**Comment by jGaboardi** [comment]
Yeah, creating it after the workshop is the best idea and I can do it unless you want to be the one to do it, no worries either way.

**Comment by martinfleis** [comment]
Given we probably talk about Zenodo archive of this repo, I'll need to do it as this repo is under my account.

**Comment by jGaboardi** [comment]
@martinfleis You were correct about Zenodo DOI creation. I thought I would be able to flip the switch since I have admin privileges, but `martinfleis/sdss22-workshop` is not showing up in my Zenodo GitHub repos.

**Comment by martinfleis** [comment]
I have switched it on.

**Comment by jGaboardi** [comment]
So I'll go ahead and (1) cut a "pre-release" [v0] then (2) add the zenodo badge and finally (3) cut the release [v1]. Right? I am always confused about the work flow.

**Comment by martinfleis** [comment]
do we need the button to be part of the release? If we do the release with this version and then add a button to have it in readme, I guess we're fine. not sure if there's a need for a second one just to get the button archived.
