### ISSUE TITLE
install from main?

### ISSUE THREAD

**Issue by jGaboardi** [martinfleis/sdss22-workshop#7]
https://github.com/martinfleis/sdss22-workshop/blob/eec3ab0803965a4219f51714feded033644f39b7/environment.yml#L5

Should we switch to be installing `momepy` from `main` for the workshop to incorporate the new patches?

```
  - pip
  - pip:
    - git+https://github.com/pysal/momepy.git@main
```

Or maybe that would screw up dependency installs due to mixing `conda` and `pip` unless we explicitly install all dependencies?

**Comment by martinfleis** [comment]
I would do a patch release of momepy within a week.
